language: java

services:
  - docker

before_install:
- docker pull nats-streaming
- docker run -p 4222:4222 -p 8222:8222 -d  nats-streaming
- docker ps -a

jdk:
- oraclejdk8

script:
- mvn clean package

branches:
  only:
    - master
    - nats
